[package]
name = "async_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-task = "3.0.0"
pin-utils = "0.1.0"
crossbeam = "0.8"
futures = "0.3.28"